# Generated by scripts/release/make-release.mjs — DO NOT HAND-EDIT.
# The sha256 below is computed from the release asset by the release job. A
# hand-pasted digest asserts what someone believed the artifact was.
class QuantumAgentOs < Formula
  desc "Quantum Agent OS"
  homepage "https://quantummemory.ai"
  # Deferral keeps the public key out of formula metadata. Redaction hides output,
  # not curl arguments. Download and unpack precede Homebrew's install-hook clear.
  # Homebrew clears sensitive variables again before post-install and formula test.
  # asset: quantum-agent-os-0.5.16-edf2d488a045.tar.gz
  # Evaluation can detect absence only: Homebrew defers every present sensitive value.
  # Empty/invalid licences must be rejected by the download provider.
  odie "Quantum needs your saved licence for this download. For updates, run quantum update. For a reinstall or repair, ask Jack." unless ENV.key?("HOMEBREW_QUANTUM_LICENCE_KEY")
  url "https://dashboard.quantummemory.ai/api/qaos/download/quantum-agent-os-0.5.16-edf2d488a045.tar.gz",
      headers: ["Authorization: Bearer #{ENV.fetch("HOMEBREW_QUANTUM_LICENCE_KEY", nil)}"]
  sha256 "edf2d488a045f22ef026488824e76e48f0b6093c7a303411a1aba8f68e4d1fa3"
  version "0.5.16"
  license :cannot_represent   # proprietary; see LICENSE in the asset

  # THE PACK IS SINGLE-ARCHITECTURE, AND THIS IS THE HONEST CONSEQUENCE. The release vendors
  # its production node_modules, and npm installs the native libsql binary for the BUILD HOST
  # only (it is an optional dependency, one package per platform). So the asset genuinely
  # cannot run elsewhere, and Homebrew's own refusal ("The arm64 architecture is
  # required for this software.") is a far better outcome than a module-resolution crash on
  # the customer's first command. Build on the other arch to ship the other arch.
  depends_on arch: :arm64
  # herdr is the ORCHESTRATION SURFACE the whole product is driven from (founder executive
  # order 2026-08-19: the entire fleet is on herdr, tmux is legacy), so one `brew install`
  # delivers both. A BARE NAME is correct here: herdr is in homebrew-core, and only a
  # dependency on ANOTHER third-party tap needs the fully-qualified user/repo/formula form.
  #
  # ⚠️ Homebrew cannot pin a dependency version, so this always tracks core's current herdr.
  # That is a real exposure with a real precedent — herdr 0.8.2's wire-protocol bump 19->20
  # once paralysed dispatch behind a green health check. The mitigation is ours and is in the
  # code (the transport adapter refuses a protocol it does not speak), not in this line.
  depends_on "herdr"
  depends_on "node"

  def install
    libexec.install Dir["*"]
    (bin/"quantum").write <<~SH
      #!/bin/bash
      exec "#{Formula["node"].opt_bin}/node" "#{libexec}/bin/quantum" "$@"
    SH
    chmod 0755, bin/"quantum"
  end

  # No service block on purpose. A launchd singleton would bound how many fleets
  # can run concurrently, and multi-fleet parallelism is a value prop.
  # Acceptance: one install, N fleets.

  def caveats
    <<~EOS
      Quantum Memory 0.5.16 is installed. Finish setup with Jack before using it.
      For updates, run quantum update. For a reinstall or repair, ask Jack.
      Check the installed version with quantum --version.
    EOS
  end

  test do
    # The installed artifact must SELF-REPORT the version this formula pins. That is the
    # whole point of shipping `quantum --version`: without it "the install matches the tag"
    # is a claim about our release notes, checkable only by reading our own paperwork.
    assert_match version.to_s, shell_output("#{bin}/quantum --version 2>&1", 0)
    assert_match "quantum", shell_output("#{bin}/quantum --help 2>&1", 0)
  end
end
